name: app python workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - 
        name: Install dependencies
        run: pip3 install -r requirements.txt
      - 
        name: Linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8
      - 
        name: Tests
        run: python3 test.py
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
      