version: '3.7'

x-logging:
  &default-logs
  driver: "json-file"
  options:
    tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 -O /dev/null http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging: *default-logs

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yaml:ro
      - /mnt/wsl-docker-containers2:/var/lib/docker/containers/:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:1080/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging: *default-logs

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            basicAuth: false
            access: proxy
            url: http://loki:3100
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging: *default-logs

  app_python:
    container_name: app_python
    image: happystove/app_python:1.0
    ports:
      - "8000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:3000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging: *default-logs
