apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_python
  labels:
    app: app_python
spec:
  selector:
    matchLabels:
      app: app_python
  template:
    metadata:
      labels:
        app: app_python
    spec:
      containers:
        - name: app_python
          image: happystove/app_python:1.0
          ports:
            - containerPort: 8080
  replicas: 2
