- name: install docker 
  pip:
    name: docker
    state: present
  tags: docker

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest
  tags: docker
  notify: start_docker
